#!/bin/bash

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


USER_DSTS=()

while read SRC DST TYPE OPTS DUMMY
do
	grep -q -E '(^|,)users?(,|$)' <<<"$OPTS" || continue

	# Append to bash array.
	USER_DSTS=("${USER_DSTS[@]}" "$DST")
done </etc/fstab

echo "User-mountable mount points: ${USER_DSTS[*]}"
